# Generated by Django 2.2.1 on 2019-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, '男'), (0, '女')], default=1, max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, '加工人员'), (2, '质检人员'), (3, '开发人员'), (4, '管理员')], default='1', max_length=8, verbose_name='人员类型'),
        ),
    ]
