# Generated by Django 2.2.1 on 2019-06-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='程序名称')),
                ('name_exe', models.CharField(max_length=128, verbose_name='程序exe名称')),
                ('path', models.CharField(max_length=128, verbose_name='程序路径')),
                ('version', models.CharField(max_length=128, verbose_name='程序版本')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '程序',
                'verbose_name_plural': '程序',
            },
        ),
        migrations.CreateModel(
            name='App_Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='参数名')),
                ('value', models.CharField(max_length=128, verbose_name='参数值')),
                ('desc', models.CharField(max_length=128, verbose_name='参数说明')),
                ('is_visiable', models.BooleanField(default=True, verbose_name='是否可见')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.App', verbose_name='程序')),
            ],
            options={
                'verbose_name': '程序参数',
                'verbose_name_plural': '程序参数',
            },
        ),
    ]
