# Generated by Django 2.2.1 on 2019-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_param',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='参数说明'),
        ),
    ]
